# Generated by Django 4.1.7 on 2023-03-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0007_auto_20230318_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='vister_data',
            name='websocket_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
