# Generated by Django 4.1.7 on 2023-03-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0008_vister_data_websocket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vister_data',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
