# Generated by Django 4.1.7 on 2023-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0010_connection_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='time_stamp',
            field=models.JSONField(null=True),
        ),
    ]
