# Generated by Django 4.1.7 on 2023-03-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0011_daily_data_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vister_data',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
