# Generated by Django 4.1.7 on 2023-03-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0012_vister_data_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vister_data',
            name='message',
            field=models.JSONField(null=True),
        ),
    ]
