# Generated by Django 4.1.7 on 2023-03-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0014_remove_vister_data_message_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='openmessage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat_message',
            name='write',
            field=models.BooleanField(default=False),
        ),
    ]
