# Generated by Django 4.1.7 on 2023-03-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0015_chat_message_openmessage_chat_message_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_message',
            name='rday',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
