# Generated by Django 4.1.7 on 2023-03-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0017_message_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='newmes',
            field=models.BooleanField(default=False),
        ),
    ]
