# Generated by Django 4.1.7 on 2023-03-30 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0018_chat_message_newmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_setup',
            name='chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotion.chat_message'),
        ),
    ]
