# Generated by Django 4.1.7 on 2023-03-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0034_alter_webservice_unique_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='4170a87c0654495c9b177f0e34dc4228', editable=False, max_length=32, unique=True),
        ),
    ]
