# Generated by Django 4.1.7 on 2023-03-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0036_alter_webservice_unique_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='e278955778ca484ebc1a93bb07d01413', editable=False, max_length=32, unique=True),
        ),
    ]
