# Generated by Django 4.1.7 on 2023-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0038_alter_webservice_unique_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='7be4ab55ce8648b086a7fa31e7a93eb5', editable=False, max_length=32, unique=True),
        ),
    ]
