# Generated by Django 4.1.7 on 2023-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0040_alter_webservice_unique_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='287f91ac6cdb44769d2771a85a3604a2', editable=False, max_length=32, unique=True),
        ),
    ]
