# Generated by Django 4.1.7 on 2023-03-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0041_alter_webservice_unique_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservice',
            name='unique_field',
            field=models.CharField(default='d15d0c70d5f74bacbc42ada508c05e1a', editable=False, max_length=32, unique=True),
        ),
    ]
